AllCops:
    NewCops: enable
    
Style/StringLiterals: 
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude: 
    - spec/**/*.rb

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/Documentation:
  Enabled: false