AllCops:
    NewCops: enable
    Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - node_modules/**/*
    - vendor/**/*
    - tmp/**/*
    
Style/StringLiterals: 
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude: 
    - spec/**/*.rb

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Exclude: 
    - bin/bundle

# Below are arbitrary limits, mostly here to put up with Rails defaults
Metrics/PerceivedComplexity:
  Max: 16

Metrics/CyclomaticComplexity:
  Max: 16 
