version: '2.1'
orbs:
  ruby: circleci/ruby@2.1.1
  node: circleci/node@5.0.2
  browser-tools: circleci/browser-tools@1.4.8
  heroku: circleci/heroku@1.2.6
jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.3-browsers # use a tailored CircleCI docker image.
        environment: 
          CIRCLE_ARTIFACTS: /tmp/test-results
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          cache-path: ~/project/node_modules/yarn.lock
          pkg-manager: yarn
  checking:
    docker:
      - image: cimg/ruby:3.2.3-browsers # use a tailored CircleCI docker image.
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
  test:
    docker:
      - image: cimg/ruby:3.2.3-browsers # use a tailored CircleCI docker image.
      - image: cimg/postgres:14.2
        environment:
          POSTGRES_DB: sheetstr_test
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: postgres
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      PGHOST: 127.0.0.1
      PGPORT: 5555
      PGPASSWORD: ''
      PGUSER: postgres
      RAILS_ENV: test
    parallelism: 3
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - ruby/install-deps
      - node/install-packages:
          cache-path: ~/project/node_modules/yarn.lock
          pkg-manager: yarn
      - run:
          command: 'dockerize -wait tcp://localhost:5555 -timeout 1m'
          name: Wait for DB
      - run:
          command: 'bundle exec rails db:schema:load --trace'
          name: Database setup
      - run: 
          command: 'bundle exec rails assets:precompile'
          name: Precompiling assets
      - ruby/rspec-test:
          include: spec/**/*_spec.rb
      - store_artifacts:
          path: /home/circleci/project/tmp/capybara
  heroku/deploy-via-git:
  Deploy-to-Fly: 
    docker: 
      - image: circleci/python
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: 
          name: Deploy to Fly.io
          command: | 
            python3 -m pip install --user ansible
            . bin/secrets/load-env
            curl -L https://fly.io/install.sh | sh
            export FLYCTL_INSTALL="/home/circleci/.fly"
            export PATH="$FLYCTL_INSTALL/bin:$PATH"
            fly deploy --app "sheetstr" --auto-confirm --access-token $FLY_ACCESS_TOKEN
 
workflows:
  build_and_test:
    jobs:
      - build
      - checking
      - test:
          requires:
            - build
      - heroku/deploy-via-git:
          requires: 
            - test
          filters:
            branches:
              only: main
      - Deploy-to-Fly:
          context: 
            - sheetstr
          requires: 
            - test
          filters:
            branches:
              only: main