version: '2.1'
orbs:
  ruby: circleci/ruby@1.7.1
  node: circleci/node@5.0.2
jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.0-node # use a tailored CircleCI docker image.
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          cache-path: yarn.lock
          pkg-manager: yarn
  checking:
    docker:
      - image: cimg/ruby:3.1.0-node # use a tailored CircleCI docker image.
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
  test:
    docker:
      - image: cimg/ruby:3.1.0-node # use a tailored CircleCI docker image.
      - environment:
          POSTGRES_DB: sheetstr_test
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: postgres
        image: cimg/postgres:14.2
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      PGHOST: 127.0.0.1
      PGPASSWORD: ''
      PGUSER: postgres
      RAILS_ENV: test
    parallelism: 3
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          cache-path: yarn.lock
          pkg-manager: yarn
      - run:
          command: 'dockerize -wait tcp://localhost:5432 -timeout 1m'
          name: Wait for DB
      - run:
          command: 'bundle exec rails db:schema:load --trace'
          name: Database setup
      - ruby/rspec-test:
          include: spec/**/*_spec.rb
workflows:
  build_and_test:
    jobs:
      - build
      - checking
      - test:
          requires:
            - build
            